# Generated by Django 5.2.4 on 2025-08-13 15:05

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload image (JPG, PNG, WebP). Max size: 10MB, Max dimensions: 4000x4000px', null=True, upload_to='profiles/', validators=[myapp.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload JPG/JPEG or PNG image. Max size: 10MB, Max dimensions: 4000x4000px', null=True, upload_to='vehicles/', validators=[myapp.models.validate_jpg_png_only]),
        ),
    ]
